org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true

android.suppressUnsupportedCompileSdk=35
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

kotlin.code.style=official

# Enable Compose metrics
# android.enableComposeCompilerMetrics=true
# android.enableComposeCompilerReports=true
